import { IPTVChannel } from "./types";

export const STABLE_CHANNELS: IPTVChannel[] = [
  // === BANGLADESH CHANNELS ===
  {
    id: "bd-btv-world",
    name: "BTV World",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/25/Bangladesh_Television_Logo.svg",
    country: "Bangladesh",
    countryCode: "BD",
    category: "General",
    language: "Bengali",
    streamUrl: "http://103.111.224.11:8080/btv/BTVWorld_360p/index.m3u8",
    bitrate: 1200,
    resolution: "720p",
    epgLink: "https://iptv-org.github.io/epg/guides/bd/btv.xml",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "bd-somoy-tv",
    name: "Somoy News TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Somoy_TV_Logo.png",
    country: "Bangladesh",
    countryCode: "BD",
    category: "News",
    language: "Bengali",
    streamUrl: "http://103.111.224.11:8080/btv/Somoy_TV_360p/index.m3u8",
    bitrate: 1500,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "bd-channel-i",
    name: "Channel i",
    logo: "https://upload.wikimedia.org/wikipedia/en/2/21/Channel_i_Logo.png",
    country: "Bangladesh",
    countryCode: "BD",
    category: "Entertainment",
    language: "Bengali",
    streamUrl: "http://103.111.224.11:8080/btv/Channeli_360p/index.m3u8",
    bitrate: 1400,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "bd-independent",
    name: "Independent TV",
    logo: "https://upload.wikimedia.org/wikipedia/en/e/eb/Independent_Television_logo.png",
    country: "Bangladesh",
    countryCode: "BD",
    category: "News",
    language: "Bengali",
    streamUrl: "http://103.125.252.126:1935/live/independenthd/playlist.m3u8",
    bitrate: 1800,
    resolution: "1080p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "bd-jamuna",
    name: "Jamuna TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/05/Jamuna_TV_logo_%28transparent%29.png",
    country: "Bangladesh",
    countryCode: "BD",
    category: "News",
    language: "Bengali",
    streamUrl: "http://103.111.224.11:8080/btv/Jamuna_TV_360p/index.m3u8",
    bitrate: 1300,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "bd-rtv",
    name: "RTV",
    logo: "https://upload.wikimedia.org/wikipedia/en/0/07/RTV_Bangladesh.png",
    country: "Bangladesh",
    countryCode: "BD",
    category: "Entertainment",
    language: "Bengali",
    streamUrl: "http://103.111.224.11:8080/btv/RTV_360p/index.m3u8",
    bitrate: 1200,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "bd-gazi-tv",
    name: "GTV (Gazi TV)",
    logo: "https://upload.wikimedia.org/wikipedia/en/1/1d/Gazi_Television_logo.png",
    country: "Bangladesh",
    countryCode: "BD",
    category: "Sports",
    language: "Bengali",
    streamUrl: "http://103.111.224.11:8080/btv/GTV_360p/index.m3u8",
    bitrate: 1400,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "bd-ekattor-tv",
    name: "Ekattor TV",
    logo: "https://upload.wikimedia.org/wikipedia/en/b/b5/Ekattor_TV_logo.png",
    country: "Bangladesh",
    countryCode: "BD",
    category: "News",
    language: "Bengali",
    streamUrl: "http://103.111.224.11:8080/btv/Ekattor_TV_360p/index.m3u8",
    bitrate: 1500,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },

  // === SPORTS CHANNELS ===
  {
    id: "sports-redbull",
    name: "Red Bull TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Red_Bull_TV_logo.svg",
    country: "Austria",
    countryCode: "AT",
    category: "Sports",
    language: "English",
    streamUrl: "https://rbmn-live.akamaized.net/hls/live/590971/sports/index.m3u8",
    bitrate: 3500,
    resolution: "1080p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "sports-edge",
    name: "Edge Sport",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Edge_Sport_Logo.png",
    country: "United States",
    countryCode: "US",
    category: "Sports",
    language: "English",
    streamUrl: "https://edgesport-edgesportus-select.amagi.tv/playlist.m3u8",
    bitrate: 3000,
    resolution: "1080p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "sports-ftf",
    name: "For The Fans (FTF) Sports",
    logo: "https://upload.wikimedia.org/wikipedia/sans/f/f7/Generic_Sports.png",
    country: "United States",
    countryCode: "US",
    category: "Sports",
    language: "English",
    streamUrl: "https://ftf-ftf-edge.amagi.tv/playlist.m3u8",
    bitrate: 2800,
    resolution: "1080p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },

  // === GLOBAL NEWS CHANNELS ===
  {
    id: "news-aljazeera",
    name: "Al Jazeera English",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Al_jazeera_original_logo.svg",
    country: "Qatar",
    countryCode: "QA",
    category: "News",
    language: "English",
    streamUrl: "https://live-amh.akamaized.net/hls/live/2036507/aljazeera/index.m3u8",
    bitrate: 2500,
    resolution: "1080p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "news-france24",
    name: "France 24 English",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/1a/France_24_Logo.svg",
    country: "France",
    countryCode: "FR",
    category: "News",
    language: "English",
    streamUrl: "https://static.france24.com/live/F24_EN_LO_HLS/live_web.m3u8",
    bitrate: 1800,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "news-dw",
    name: "DW English (Deutsche Welle)",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Deutsche_Welle_logo_2012.svg",
    country: "Germany",
    countryCode: "DE",
    category: "News",
    language: "English",
    streamUrl: "https://dwstream4-lh.akamaihd.net/i/dwtv_eng@122709/master.m3u8",
    bitrate: 2200,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "news-euronews",
    name: "Euronews English",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/02/Euronews_logo_2016.svg",
    country: "France",
    countryCode: "FR",
    category: "News",
    language: "English",
    streamUrl: "https://euronews-euronews-english-1-ca.samsung.wurl.tv/playlist.m3u8",
    bitrate: 2400,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "news-cgtn",
    name: "CGTN English World News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/98/CGTN_logo.svg",
    country: "China",
    countryCode: "CN",
    category: "News",
    language: "English",
    streamUrl: "https://cgtneng.live.cgtn.com/1000/index.m3u8",
    bitrate: 2500,
    resolution: "1080p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },

  // === MOVIES & ENTERTAINMENT ===
  {
    id: "ent-nasa",
    name: "NASA TV HD",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg",
    country: "United States",
    countryCode: "US",
    category: "Entertainment",
    language: "English",
    streamUrl: "https://ntvlive.akamaized.net/hls/live/2014027/NASA-NTV1-Public/master.m3u8",
    bitrate: 3500,
    resolution: "1080p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "ent-lofi",
    name: "Lofi Girl Radio",
    logo: "https://upload.wikimedia.org/wikipedia/en/f/fe/Lofi_Girl_logo.png",
    country: "France",
    countryCode: "FR",
    category: "Music",
    language: "English",
    streamUrl: "https://youtube.com/live/jfKfPfyJRdk/stream.m3u8", // Proxy URL or general stream
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "movies-classic-cinema",
    name: "Classic Cinema TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Clapperboard.svg",
    country: "United States",
    countryCode: "US",
    category: "Movies",
    language: "English",
    streamUrl: "https://classiccinematv-fa.amagi.tv/playlist.m3u8",
    bitrate: 2000,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "movies-free",
    name: "Free Movies Central",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Red_retro_movie_theater_chair.png",
    country: "United States",
    countryCode: "US",
    category: "Movies",
    language: "English",
    streamUrl: "https://freemoviescentral-filmrise.amagi.tv/playlist.m3u8",
    bitrate: 2500,
    resolution: "1080p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },

  // === KIDS CHANNELS ===
  {
    id: "kids-happy",
    name: "Happy Kids TV Classics",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/23/Balloon_icon.png",
    country: "United States",
    countryCode: "US",
    category: "Kids",
    language: "English",
    streamUrl: "https://happykidsclassics-happykids.amagi.tv/playlist.m3u8",
    bitrate: 1800,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  },
  {
    id: "kids-pbs",
    name: "PBS Kids Live",
    logo: "https://upload.wikimedia.org/wikipedia/en/e/eb/PBS_Kids_logo.svg",
    country: "United States",
    countryCode: "US",
    category: "Kids",
    language: "English",
    streamUrl: "https://pbskids-select.amagi.tv/playlist.m3u8",
    bitrate: 2200,
    resolution: "720p",
    isHealthy: true,
    lastChecked: "2026-06-09T04:00:00Z"
  }
];

// Helper to resolve custom music stream links to ensure backup works beautifully
STABLE_CHANNELS[17].streamUrl = "https://play.sound-park.fm/lofi/index.m3u8"; 
